const actionTypes = {
  AUTH: {
    GET_ACCESS_TOKEN_SUCCESS: 'AUTH-GET_ACCESS_TOKEN_SUCCESS',
    GET_ACCESS_TOKEN_FAIL: 'AUTH-GET_ACCESS_TOKEN_FAIL',
  },
  USER: {
    GET_USER_DETAIL: 'USER-GET_USER_DETAIL',
    GET_USER_DETAIL_SUCCESS: 'USER-GET_USER_DETAIL_SUCCESS',
    GET_USER_DETAIL_FAIL: 'USER-GET_USER_DETAIL_FAIL',
  },
};

export default actionTypes;
