const actionTypes = {
  AUTH: {
    GET_ACCESS_TOKEN: 'AUTH-GET_ACCESS_TOKEN',
    GET_ACCESS_TOKEN_SUCCESS: 'AUTH-GET_ACCESS_TOKEN_SUCCESS',
    GET_ACCESS_TOKEN_FAIL: 'AUTH-GET_ACCESS_TOKEN_FAIL',
  },
};

export default actionTypes;
